name: cyphershield_frontend

description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0              # Backend API calls
  provider: ^6.1.0          # State management
  fluttertoast: ^8.2.1      # Quick notifications
  go_router: ^13.1.0        # Navigation & Routing
  flutter_screenutil: ^5.9.0 # Responsive UI
  google_fonts: ^6.2.1      # Custom fonts
  shared_preferences: ^2.2.3 # Local storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bgimg.png
